Simplify multi-arch support

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,9 +1,13 @@
 set -euo pipefail
 
-DOCKER_USER="hkjn"
-DOCKER_IMAGE="certs"
-CPU_ARCH="$(uname -m)"
-TAG="${DOCKER_USER}/${DOCKER_IMAGE}:${CPU_ARCH}"
+declare DOCKER_USER="hkjn"
+declare DOCKER_IMAGE="certs"
+declare CPU_ARCH="$(uname -m)"
+declare -A DOCKER_ARCHS
+DOCKER_ARCHS["x86_64"]="amd64"
+DOCKER_ARCHS["armv7l"]="arm"
+declare DOCKER_ARCH=${DOCKER_ARCHS[${CPU_ARCH}]}
+declare TAG="${DOCKER_USER}/${DOCKER_IMAGE}:${DOCKER_ARCH}"
 
 docker build -t ${TAG} .
 NO_PUSH=${NO_PUSH:-""}
@@ -11,3 +15,9 @@ if [[ ! "${NO_PUSH}" ]]; then
   docker push ${TAG}
 fi
 
+if ! which manifest-tool 1>/dev/null; then
+        echo "FATAL: No manifest-tool found on PATH, can't push multi-arch manifests." >&2
+        exit 1
+fi
+echo "Pushing multi-arch manifests.."
+manifest-tool push from-args --platforms linux/amd64,linux/arm --template hkjn/certs:ARCH --target hkjn/certs
